config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#index'
  get 'contacts/new'
  post 'contacts/create'
  
  root 'home#index'
  get 'home/index'
  get 'home/indice'
  get 'home/about'
  get 'home/portafolio'
  get 'home/portafolio2'
  get 'home/website'
  get 'home/contact_us'
  get 'home/expertise'
  get 'home/searcher'
    get 'home/searched'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
    resources :contacts, only: [:new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates :name, presence: true
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	#include Pagy::Backend
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
     @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      # Send email here (you'll need to configure your email settings)
      #UserMailer.welcome.deliver_later
      #ContactMailer.send_email.deliver_now
      ContactMailer.send_email(@contact).deliver_now
      flash[:success] = 'Email sent successfully.'
      redirect_to new_contact_path
    else
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
   
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
require 'date'

  def about #this is about method
    @about_me = "Enhancing the design of a construction project is crucial, not only to meet the client's requirements but also to improve the outcomes for all stakeholders involved in the project-construction process." 
    @name = "My name is Paul Ordonez and Estrutecnia is established"
    @answer = 2023-2017 
  end

  def acerca #this is acerca method
    @about_me = "Somos un equipo de profesionales comprometidos en brindar soluciones efectivas a nuestros clientes"
    
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = box.ransack(params[:q])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	#include Pagy::Frontend
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/contacts/new.html.erb
<%= render 'shared/navbar_en' %>
<div class="container">
<h1>Contact Us</h1>
<p>Please fill your contact information, we will reply as soon as we can.</p>
<%= form_with(model: @contact, url: contacts_path, method: :post) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  
  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>
  
  <div class="actions">
    <%= form.submit 'Send Email' %>
  </div>
<% end %>
</div>

app/views/home/about.html.erb
<%= render 'shared/navbar_en' %>

<div class="container">
	<br>
<h1>About us...</h1> <!--The view>page-->

<p>
	<%= @about_me %> <br></br> <%= @name %> since 2017, <%= @answer %> years ago
</p>

app/views/home/acerca.html.erb
<%= render 'shared/navbar_es' %>

<div class="container">
<br>
	<h1>Portafolio</h1> 

<p>
	<%= @about_me %>
</p>
<h6> A continuación una muestra de nuestros proyectos representativos</h6>
<head>
	<link rel="stylesheet" href="style.css">
</head>
<!-- <div id="pins"> -->
	<!--<div class="grid"> -->
		<div class="container">

	<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix">
   <div class="box col3">
    Puente Guagrayacu, Napo
    <%= image_tag "guagrayacu.jpg", width: 400  %>
  </div>
  
<div class="box col4">
    Puente Oritoyacu, Napo
    <%= image_tag "oritoyacu.jpg", width: 400  %>
  </div>
	  <div class="box col4">
	    Diseño estructural Edificios Prados de San Mateo</br>
	    <%= image_tag "pradosdesanmateo.PNG", width: 400  %>
	  </div>
	  <div class="box col5">
	    Construcción Edificio Centro Universitario de Idiomas UCE</br>
	    <%= image_tag "UCE.jpg", width: 400  %>
	  </div>

	  <div class="box col6">
Construcción Campamento Hidroeléctrica CocaSinclair</br>
    <%= image_tag "Campamento coca sinclair 20120425_095603.jpg", width: 300  %>
  </div>
  <div class="box col7">
Señalización vial y seguridad vial Ampliación Santo Domingo de los Tsáchilas - Unión del Toachi, Eje E20</br>
    <%= image_tag "toachi.jpg", width: 300  %>
  </div>
<div class="box col8">
    <br> Sistema de agua potable embajada de EeUu</br>
    <%= image_tag "water system.PNG", width: 300  %>
  </div>
<div class="box col9">
   Sistemas Building Information Sistem para construcciones, modelos de Revit</br>
    <%= image_tag "revit haus pillagua render.jpg", width: 300  %>
  </div>
<div class="box col10">
    Señalización en Eje Panamericano E35
    <%= image_tag "2loja.jpg", width: 400  %>
  </div>
  
 
  </div>
</div>
</div>
Contactos al +593 99 822 1378
<p>
</p>

app/views/home/contact_us.html.erb
<%= render 'shared/navbar_es' %>

<br>
	<h1>Contact Us</h1>
	<p> También nos dedicamos al diseño web, he aquí una muestra de lo que podemos hacer </p>
	
	<p> Put </p>
	
	        <%= image_tag "pinterested.png", width: 800  %>

app/views/home/expertise.html.erb
<%= render 'shared/navbar_en' %>
<br>
<div class="container">
	<h1>Estrutecnia</h1>
<p>Here is a sample of what we can do</p>

<div class="container">
<br>
		        <%= image_tag "pinterested.png", width: 800  %>
<% if render='shared/navbar_es' %>
	<p> <br> Don't forget to contact us, for more information</p>
	<% else %>
	<p> Put </p>
	<% end %>

app/views/home/index.html.erb
<%= render 'shared/navbar_en' %>
<br>
<div class="container">
	<h1>Estrutecnia</h1>
<p>Technical structuring</p>

app/views/home/indice.html.erb
<%= render 'shared/navbar_es' %>
<div class="container">
	<br>
<h1>Estrutecnia</h1>
<p>Estructuras y Geotecnia una empresa internacional</p>

app/views/home/portafolio.html.erb
<%= render 'shared/navbar_es' %>

<div class="container">
<br>
	<h1>Portafolio</h1> 

<p>
	<%= @about_me %>
</p>
<h6> A continuación una muestra de nuestros proyectos representativos</h6>
<head>
	<link rel="stylesheet" href="style.css">
</head>
<!-- <div id="pins"> -->
	<!--<div class="grid"> -->
		<div class="container">

	<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix">
   <div class="box col1">
    Puente Guagrayacu, Napo
    <%= image_tag "guagrayacu.jpg", width: 400  %>
  </div>
  
<div class="box col2">
    Puente Oritoyacu, Napo
    <%= image_tag "oritoyacu.jpg", width: 400  %>
  </div>
	  <div class="boxo col3">
	    Diseño estructural Edificios Prados de San Mateo</br>
	    <%= image_tag "pradosdesanmateo.PNG", width: 400  %>
	  </div>
	  <div class="box col5">
	    Construcción Edificio Centro Universitario de Idiomas UCE</br>
	    <%= image_tag "UCE.jpg", width: 400  %>
	  </div>

	  <div class="box col6">
Construcción Campamento Hidroeléctrica CocaSinclair</br>
    <%= image_tag "Campamento coca sinclair 20120425_095603.jpg", width: 300  %>
  </div>
  <div class="box col7">
Señalización vial y seguridad vial Ampliación Santo Domingo de los Tsáchilas - Unión del Toachi, Eje E20</br>
    <%= image_tag "toachi.jpg", width: 300  %>
  </div>
<div class="box col8">
    <br> Sistema de agua potable embajada de EeUu</br>
    <%= image_tag "water system.PNG", width: 300  %>
  </div>
<div class="box col9">
   Sistemas Building Information Sistem para construcciones, modelos de Revit</br>
    <%= image_tag "revit haus pillagua render.jpg", width: 300  %>
  </div>
<div class="box col10">
    Señalización en Eje Panamericano E35
    <%= image_tag "2loja.jpg", width: 400  %>
  </div>
  
 
</div>
  </div>
</div>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item"><a class="page-link" href="#">Previa</a></li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="/home/portafolio2">2</a></li>
    <li class="page-item"><a class="page-link" href="/home/portafolio2">Siguiente</a></li>
  </ul>
</nav>
</div>
Contactos al +593 99 822 1378
<p>
</p>

app/views/home/portafolio2.html.erb
<%= render 'shared/navbar_es' %>

<div class="container">
<br>
	<h1>Portafolio</h1> 

<p>
	<%= @about_me %>
</p>
<h6> A continuación una muestra de nuestros proyectos representativos</h6>
<head>
	<link rel="stylesheet" href="style.css">
</head>
<!-- <div id="pins"> -->
	<!--<div class="grid"> -->
		<div class="container">
    <div id="masonry-container" class="transitions-enabled infinite-scroll clearfix">


        <div class="boxo col11">
    Ensayos de Suelos para Edificaciones
    <%= image_tag "spt.jpeg", width: 400  %>
  </div>
  <div class="box col12">
        Diseños de Agua Potable y Alcantarillado<br/>
        <%= image_tag "HIDROSANITARI.png", width: 400  %>
      </div>
        <div class="box col13">
        Planos estructurales<br/>
        <%= image_tag "estructurais.png", width: 400  %>
      </div>
        <div class="box col14">
        Analisis estructurales de cisternas, cavas o diversas estructuras<br/>
        <%= image_tag "cava1.png", width: 400  %>
      </div>
  <div class="box col15">
        Analisis de Geoestructuras en 2D<br/>
        <%= image_tag "plaxis2D.png", width: 400  %>
      </div>
	  <div class="box col16">
        Modelos de Elementos Finitos en Geoestructuras en 3D<br/>
        <%= image_tag "plaxis3D.png", width: 400  %>
      </div>
<div class="boxo col17">
        Paginas Web<br/>
        <%= link_to image_tag("pinterested.png"), "website"  %>
      </div>
          <div class="box col18">
        Instalación de diversos programas</br>
        <%= image_tag "Pagination · Bootstrap v5.3.png", width: 400  %>
      </div>

 
</div>
  </div>
</div>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item"><a class="page-link" href="<%= home_portafolio_path %>">Previa</a></li>
    <li class="page-item"><a class="page-link" href="<%= home_portafolio_path    %>">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">Siguiente</a></li>
  </ul>
</nav>
</div>
Contactos al +593 99 822 1378
<p>
</p>

app/views/home/searched.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" >
        <title>Autocomplete SearchBar-Easy Tutorials</title>
        <link rel="stylesheet" type="styler.css" href="">
        <script src="https://kit.fontawesome.com/298d666e8d.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="search-box">
            <div class="row">
                <input type="text" id="input-box" placeholder="Search anything" autocomplete="off">
                 <button><i class="fa-solid fa-magnifying-glass"></i></button>
            </div>
            <div class="result-box">
                <ul>
                    <li>Webpages</li>
                    <li>JavaScript</li>
                </ul>
                </div>
        </div>
    </body>
</html>

app/views/home/searcher.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Autocomplete SearchBar</title>
        <link rel="stylesheet" type="styler.css" href="">
        <script type="text/javascript">


            function sendToPage(){
                var input = document.getElementById("search").value;
                 //alert(input);
                if (input == "happy"){
                    location.href = "suggestion_happy.html";
                    return false;
                }
                else if (input == "sad"){
                    location.href = "suggestion_sad.html";
                    return false;
                }
                else {
                    alert('Invalid Input.');
                }
                    }
        </script>
    </head>
    <body>
        <div>
                <input type="text" method="put" id="search" placeholder="Search" value="">
                <input type='submit' onclick="sendToPage();" />
        </div>
        <div class="search-box">
            <div class="row">
                <input type="text" id="input-box" placeholder="Search anything" autocomplete="off">
                <button>search</button>
            </div>
            
        </div>
    </body>
</html>

app/views/home/website.html.erb
<%= render 'shared/navbar_es' %>

<div class="container">
<br>
	<h1>Website</h1>
	<% if render='shared/navbar_es' %>
	<p> También nos dedicamos al diseño web, he aquí una muestra de lo que podemos hacer </p>
	<% else %>
	<p> Put </p>
	<% end %>
	        <%= image_tag "pinterested.png", width: 800  %>
<% if render='shared/navbar_es' %>
	<p> <br> No olvides contactarnos, para obtener más información </p>
	<% else %>
	<p> Put </p>
	<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    



    <title>Estrutecnia where ideas collude</title> <!-- this title goes in the pestaña -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

<!-- %= render 'home/header' %> #here a render was putted, to link to a Partial that goes to _header in views>home -->

     <%= yield %>
     </div>
     <footer>
      <div class="container">
    <p>&copy; <%= Time.current.year %> My Website. All rights reserved.</p>
    <p>Contact: +593 9 9822 1378 email: estrutecnia@petalmail.com</p>
  </div>
  </footer>
  </body>
</html>

app/views/search/_form.html.erb
<%= search_form_for(@query, url:search_path, method :get, class:'d-flex') do |f| %>
    <%= f.search_field :title_or_body_or_user_email_or_user_name_i_cont_any, placeholder: "Search...",
    class: "form-control me-2" %>
    <%= f.submit "Search!", class: "btn btn-outline-success"  %>
<% end %>

app/views/search/index.html.erb
<h1>Search#index</h1>
<p>Find me in app/views/search/index.html.erb</p>

<%= render 'search/form' %>

app/views/shared/_navbar_en.html.erb
 <!--<              bg-primary" data-bs-theme="dark"> -->
 <nav class="navbar navbar-expand-lg bg-primary " data-bs-theme="dark"> 
  <div class="container-fluid">
   <!-- <a class="navbar-brand" href="#">Estrutecnia</a> -->
 <a class="navbar-brand" href="/home/index">
       <!-- <img src="/assets/images/logo.png" alt="Estrutecnia" width="3" height="2">  -->
       <%= image_tag('bootstrap-logo.svg', class: "navbar-logo", alt: "Estrutecnia")  %>
       <%= stylesheet_link_tag "logo" %>
    </a> 


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-auto"> <!-- ms-auto makes home link dropdown to the very right-->
        
          <a class="nav-link active" aria-current="page" href="/home/about">About</a>
        </li>
                <!--<li class="nav-item">
          <a class="nav-link" href="/home/index">English</a>
        </li> -->
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/home/expertise">Expertise</a>
        </li>
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="/contacts/new">Contact Us</a></li>
  <li class="nav-item">

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            More
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Construction</a></li>
            <li><a class="dropdown-item" href="#">Consultacy</a></li>
            <li><a class="dropdown-item" href="#">Sustainability</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" aria-current="page" href="/contacts/new">Contact Us</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">EN</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/home/indice">ES</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>

</nav>

app/views/shared/_navbar_es.html.erb
 <!--<              bg-primary" data-bs-theme="dark"> -->
 <nav class="navbar navbar-expand-lg bg-primary " data-bs-theme="dark"> <!-- dark-->
  <div class="container-fluid">
   <!-- <a class="navbar-brand" href="#">Estrutecnia</a> -->
 <a class="navbar-brand" href="/home/index">
       <!-- <img src="/assets/images/logo.png" alt="Estrutecnia" width="3" height="2">  -->
       <%= image_tag('bootstrap-logo.svg', class: "navbar-logo", alt: "Estrutecnia")  %>
       <%= stylesheet_link_tag "logo" %>
    </a> 



    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-auto"> <!-- ms-auto makes home link dropdown to the very right-->
        
        <a class="nav-link active" aria-current="page" href="/home/indice">Inicio</a>
        <a class="nav-link active" aria-current="page" href="/home/portafolio">Portafolio</a>
<a class="nav-link active" aria-current="page" href="/home/acerca">Servicios</a>
          <a class="nav-link active" aria-current="page" href="/home/acerca">Nosotros</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/home/contact_us">Contactanos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/home/index">English</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Mas
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Construcción</a></li>
            <li><a class="dropdown-item" href="#">Consultoría</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Contactenos</a></li>
          </ul>
        </li>
       <!-- <li class="nav-item">
          <a class="nav-link disabled">Es</a>
        </li> -->
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Buscar</button>
      </form>
    </div>
  </div>

</nav>